// Generated by CoffeeScript 1.6.3
(function() {
  var YAMLCompiler, yaml;

  yaml = require("js-yaml");

  module.exports = YAMLCompiler = (function() {
    YAMLCompiler.prototype.brunchPlugin = true;

    YAMLCompiler.prototype.type = "javascript";

    YAMLCompiler.prototype.extension = "yaml";

    function YAMLCompiler(config) {
      this.config = config;
      return;
    }

    YAMLCompiler.prototype.compile = function(data, path, cb) {
      var err, json, loaded, msg;
      try {
        loaded = yaml.load(data, {
          filename: path
        });
      } catch (_error) {
        err = _error;
        msg = err.mark != null ? "" + (err.mark.line + 1) + ":" + (err.mark.column + 1) + " " + err.reason : err.toString();
        cb(msg);
        return;
      }
      try {
        json = JSON.stringify(loaded);
      } catch (_error) {
        err = _error;
        cb(err.toString());
        return;
      }
      return cb(null, "module.exports = " + json);
    };

    return YAMLCompiler;

  })();

}).call(this);
